# IPython log file

get_ipython().run_line_magic('logstart', './ipython_session.py')
get_ipython().run_line_magic('matplotlib', '')
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
from matplotlib import pyplot as plt
from nmrgraphs import *
fig1, ax1 = plt.subplots()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
ytl = list()
for item in ax1.get_yticklabels():
    text = item.get_text()
    if '\u22121.00' == text:
        text = r'$-M_0$'
    elif '1.00' == text:
        text = r'$M_0$'
    else:
        text = r''
    ytl.append(text)
ax1.set_yticklabels(ytl)
quit()
get_ipython().run_line_magic('logstart', './ipython_session.py append')
get_ipython().run_line_magic('matplotlib', '')
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
from matplotlib import pyplot as plt
from nmrgraphs import *
fig1, ax1 = plt.subplots()
t1_relax_graph(ax1, 8, 1, 1, 2)
quit()
get_ipython().run_line_magic('logstart', './ipython_session.py append')
get_ipython().run_line_magic('matplotlib', '')
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
from matplotlib import pyplot as plt
from nmrgraphs import *
fig1, ax1 = plt.subplots()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
quit()
get_ipython().run_line_magic('logstart', './ipython_session.py append')
get_ipython().run_line_magic('matplotlib', '')
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
from matplotlib import pyplot as plt
from nmrgraphs import *
fig1, ax1 = plt.subplots()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
for item in ax1.get_xticklabels():
    print(item.get_text())
    print(item.get_position())
    
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
$clear
get_ipython().run_line_magic('clear', '')
t1_relax_graph(ax1, 8, 1, 1, 2)
for item in ax1.get_xticklabels():
    print(item.get_text())
    print(item.get_position())
    
for item in ax1.get_yticklabels():
    print(item.get_text())
    print(item.get_position())
    
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
for item in ax1.get_xticklabels():
    print(item.get_text())
    print(item.get_position())
    
for item in ax1.get_yticklabels():
    print(item.get_text())
    print(item.get_position())
    
ax1.cla()
get_ipython().run_line_magic('clear', '')
t1_relax_graph(ax1, 8, 1, 1, 2)
ax1.cla()
t1_relax_graph(ax1, 8, 1, 1, 2)
for item in ax1.get_xticklabels():
    print(item.get_text())
    print(item.get_position())
    
for item in ax1.get_yticklabels():
    print(item.get_text())
    print(item.get_position())
    
get_ipython().run_line_magic('logstart', './ipython_session.py append')
get_ipython().run_line_magic('matplotlib', '')
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
from matplotlib import pyplot as plt
from nmrgraphs import *
fig1, ax1 = plt.subplots()
t1_relax_plot(ax1, 8.0, 1.0, 1.0, 2.0, 2.0, 6.0)
ax1.cla()
quit()
get_ipython().run_line_magic('logstart', './ipython_session.py append')
get_ipython().run_line_magic('matplotlib', '')
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
from matplotlib import pyplot as plt
from nmrgraphs import *
fig1, ax1 = plt.subplots()
t2_relax_plot(ax1, 8.0, 1.0, 2.0, 2.0, 6.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 8.0, 16.0, 0.5, 6.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 2.0, 4.0, 0.5, 6.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 2.0, 6.0, 0.5, 6.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 6.0, 0.5, 6.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.5, 4.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
ax1.cla()
t2_relax_plot(ax1, 8.0, 1.5, 5.0, 0.4, 3.0)
quit()
get_ipython().run_line_magic('logstart', './ipython_session.py append')
get_ipython().run_line_magic('matplotlib', '')
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
from matplotlib import pyplot as plt
from nmrgraphs import *
fig1, ax1 = plt.subplots()
gradient_field_plot(ax1, 4.0, 0.5, 1)
quit()
get_ipython().run_line_magic('logstart', './ipython_session.py append')
get_ipython().run_line_magic('matplotlib', '')
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')
from matplotlib import pyplot as plt
from nmrgraphs import *
fig1, ax1 = plt.subplots()
gradient_field_plot(ax1, 4.0, 0.5, 1)
ax1.cla()
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.4, 1)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.3, 1)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.3, 1)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.2, 3)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
xrange(-4.0, 4.0, 0.5)
range(-4.0, 4.0, 0.5)
np.arange(-4.0, 4.0, 0.5)
'  '.join(dir(np.arange(-4.0, 4.0, 0.5)))
np.arange(-4.0, 4.0, 0.5).tolist()
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
get_ipython().run_line_magic('pinfo', 'np.array')
get_ipython().run_line_magic('pinfo', 'np.array.fill')
get_ipython().run_line_magic('pinfo', 'np.array')
' '.join(dir(np.arange(-4.0, 4.0, 0.5)))
type(np.arange(-4.0, 4.0, 0.5))
get_ipython().run_line_magic('pinfo', 'numpy.ndarray.fill')
get_ipython().run_line_magic('pinfo', 'numpy.ndarray')
get_ipython().run_line_magic('pinfo', 'np.ndarray.fill')
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
ax1.cla()
gradient_field_plot(ax1, 4.0, 0.25, 2)
quit()
